blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: {{ cookiecutter.repository }} / docs
    about: Please consult the documentation before creating an issue.
  - name: Community
    url: https://discord.com/invite/{{ cookiecutter.package_name }}
    about: Join our Discord community to ask questions and collaborate.
