blank_issues_enabled: true
#contact_links:
#  - name: Documentation
#    url: https://github.com/JnyJny/python-package-cookiecutter/docs
#    about: Please consult the documentation before creating an issue.
#  - name: Community
#    url: https://discord.com/invite/python-package-cookiecutter
#    about: Join our Discord community to ask questions and collaborate.
